name: General CI

on:
  workflow_call:
    inputs:
      arch:
        type: string
        required: false
        description: "CPU Architecture"
        default: aarch64
      libc:
        type: string
        required: false
        description: "LIBC name"
        default: musl
      python_ver:
        type: string
        required: false
        description: "Python version"
        default: 3.9.7      
  
  workflow_dispatch:
    inputs:
      arch:
        required: true
        description: "CPU Architecture"
        default: aarch64
      libc:
        required: true
        description: "LIBC name"
        type: choice
        options:
          - musl
          - uclibc
          - glibc
        default: musl
      python_ver:
        type: string
        required: true
        description: "Python version"
        default: 3.9.7

jobs:
  build_docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --build-arg=ARCH=${{ inputs.arch }} --build-arg=LIBC=${{ inputs.libc }} --build-arg=PYTHON_VER=${{ inputs.python_ver }} --tag static-python-maker .
    - name: Run the Docker image
      run: docker run --name static-python-container static-python-maker
    - name: Get output binary out of docker
      run: docker cp static-python-container:/app/final/static_python .
    - name: Upload docker result
      uses: actions/upload-artifact@v3
      with:
        name: static_python_docker
        path: ./static_python
    - name: to release packages
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.REPO_TOKEN }}
        file: ./static_python
        asset_name: static_python_${{ inputs.arch }}_${{inputs.libc}}
        tag: ${{ inputs.arch }}_${{inputs.libc}}
        overwrite: true
        body: "compile kubeadm in github action"
        file_glob: true
        
